add docstrings to all functions
SBC-Utrecht/pytom-template-matching-gpu pull request #100
Opened 2024-02-12 15:50 UTC by McHaillet

This is a draft PR to expand and update the docstrings of the code.

Closes #8

2024-02-13 16:01 UTC, sroet requested changes
quite some issues, most of them about how to describe defaults in the docstrings.
Feel free to ignore them, if you don't agree with this way of mentioning defaults

2024-02-13 16:27 UTC, McHaillet commented on src/pytom_tm/correlation.py
> +    output: Union[float, cpt.NDArray[float]]
If it is done via cupy it will return a cupy array with a single value

2024-02-14 09:07 UTC, sroet requested changes
2 leftover issues from the previous round, LGTM otherwise

2024-02-14 09:07 UTC, sroet commented on src/pytom_tm/template.py
> +    ctf_params: Optional[dict]
This is still relevant

2024-02-14 09:07 UTC, sroet commented on src/pytom_tm/tmjob.py
> +        return_volumes: bool
still not resolved

2024-02-14 09:12 UTC, sroet commented
Hmm, this unfortunately did not grab the parent comments, but those lines are still missing defaults 😄 and where mentioned [here](https://github.com/SBC-Utrecht/pytom-template-matching-gpu/pull/100#discussion_r1488098806) and [here](https://github.com/SBC-Utrecht/pytom-template-matching-gpu/pull/100#discussion_r1488130276)

2024-02-14 09:55 UTC, McHaillet commented
thanks for the links, yep now they are resolved!

2024-02-14 10:29 UTC, sroet approved these changes
LGTM, feel free to merge

2024-02-14 10:47 UTC, merged