Patch unittest inconsistency
SBC-Utrecht/pytom-template-matching-gpu pull request #66
Opened 2023-11-16 16:24 UTC by McHaillet

Closes #58. 

It works! :relieved:

- Both the test_parallel_manager and test_tm_job_split_volume now only compare the score and angle volume with a distance of template_size // 2 from the edge as we expect numerical inaccuracies in those regions.
- test_tm_job_split_volume now splits along each dimensions (2,3,2) creating 12 subvolumes 
- test_parallel_manager still only splits (1,3,1) as this test should just check the parallel managing part

2023-11-16 16:34 UTC, McHaillet commented
Added a test that checks whether split volume raises the correct error with too small pieces

2023-11-16 17:00 UTC, sroet requested changes
Small readability improvement, LGTM othewise

2023-11-17 09:47 UTC, McHaillet commented
Added your suggestions and checked that the tests still succeed!

2023-11-17 09:48 UTC, sroet approved these changes
LGTM, feel free to merge

2023-11-17 09:48 UTC, merged